/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_919077_8_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_919077_1[] = { "double_tap", "flick", "lift", "rotate", "shake" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_919077_12_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
const uint32_t ei_dsp_config_919077_12_axes_size = 8;
ei_dsp_config_spectral_analysis_t ei_dsp_config_919077_12 = {
    12, // uint32_t blockId
    4, // int implementationVersion
    8, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    10.0f, // float filter-cutoff
    2, // int filter-order
    "FFT", // select analysis-type
    8, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_919077_12[56] = { 0.37987534277606755, -0.12256499905837699, 0.35696728707291187, 1.303059365078807, -0.0779923435091041, -0.8723527521826326, -1.5169449571659788, 0.12288516080938279, -0.13798697682330385, 1.188947753359098, 1.2801316065201536, -0.09781700186198578, -1.44191736536799, -2.0036790984589605, 0.3838647999241948, -1.2034651856322307, 11.357926779320696, 1.100520201807376, -0.299355898257345, -0.5156691147390666, -0.9452724171429873, 0.20390547838062048, -2.908958382936544, 26.61301880334504, 0.62149513734621, -0.9090782982646488, -0.5687190947961063, -0.9275704731792211, 2.7465309807658196, -0.28029204324353485, 3.9139873483777046, 1.1924071829020977, -0.2853971390188235, 1.6100334447249771, 0.8448943576775492, 8.364548762887717, -0.015105782328027999, 3.125852941768244, 1.251742532402277, -0.17374122091569005, 2.0321548255067317, 1.3287694488605484, 3.865424387603998, 0.11298470459878444, 3.3969082801882178, 1.170404277741909, -0.3209509409731254, 1.571547928697837, 0.8035549667431041, 8.001557024568319, 1.3950670843431725, 2.62596879072953, 1.359043278247118, 0.014571073494153097, 2.08393968205899, 1.3219592535536504 };
const float ei_dn_standard_scaler_scale_919077_12[56] = { 2.5948661062723613, 1.0192161938677273, 0.3237293582679245, 3.4743106248897933, 2.021247409413403, 1.0072665316258003, 1.0761354782704977, 7.6204746965485235, 0.9657917148485499, 0.1632764729873621, 3.176857552489785, 2.069393254090727, 1.4807520390282838, 1.6093595053154461, 3.746070617352453, 0.37169840282232175, 0.040536565149478905, 1.782319830578007, 1.3622954680362067, 2.9429818879462935, 5.169788227150692, 6.384618919974254, 0.3216311534230556, 0.034008922645083, 1.6268894224695876, 1.3539808561728193, 2.718720830024544, 7.589593042397011, 0.4300045961170203, 0.65094088030461, 0.15403325693084455, 2.9733817039657118, 1.607543611846363, 1.5124665868965999, 1.5936475510043324, 0.11259735165313631, 0.628771215203632, 0.20834225000676734, 3.0063396599292593, 1.6881284112375616, 1.0610640189507032, 1.0971956516008912, 0.18718846640418524, 0.7818582109374168, 0.2179956024997909, 3.0841819111245474, 1.6513081482642105, 1.0920849226699716, 1.1424954654492177, 0.14136912498347454, 0.8726397723165639, 0.19572258853652652, 4.573413167378845, 2.55742668915573, 1.0647394833475006, 1.1073336636238442 };
const float ei_dn_standard_scaler_var_919077_12[56] = { 0.1485149225925991, 0.9626476817320127, 9.541921234929376, 0.082844314952646, 0.24477161167075298, 0.9856238232503616, 0.8635074739886874, 0.01722011110717591, 1.0720944533482426, 37.51049361048665, 0.09908422486365545, 0.23351454777937064, 0.4560740070856169, 0.3860947188039613, 0.07126037114526004, 7.238000522164609, 608.56378969248, 0.31479564939100957, 0.5388369587868088, 0.11545821032034026, 0.03741575331445388, 0.02453183522123803, 9.66682337645842, 864.5980493615358, 0.37781911723398776, 0.5454751270594735, 0.13529158062192298, 0.017360531658398074, 5.408213212840833, 2.3600266447524856, 42.14742079926862, 0.11310939266382813, 0.38696748251746854, 0.437147925559265, 0.39374535242724285, 78.87577661919508, 2.5293835894628534, 23.03802790111292, 0.11064299105495691, 0.35090458412303965, 0.8882123850351085, 0.83067634727284, 28.539202141267126, 1.6358519543368206, 21.04284877660507, 0.10512839368616252, 0.36672773165325956, 0.8384693224417018, 0.7661098213478525, 50.03695354463604, 1.3131973392379825, 26.10466343064105, 0.04781004190747693, 0.15289511633961694, 0.8820907780384023, 0.815535732179506 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_919077_12 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_919077_12,
    .mean_data_len = 56,
    .scale_data = (float *)ei_dn_standard_scaler_scale_919077_12,
    .scale_data_len = 56,
    .var_data = (float *)ei_dn_standard_scaler_var_919077_12,
    .var_data_len = 56
};
ei_data_normalization_t ei_data_normalization_config_919077_12 = {
    (void *) &ei_data_normalization_standard_scaler_config_919077_12, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_919077_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_919077_1[ei_dsp_blocks_919077_1_size] = {
    { // DSP block 12
        12,
        56, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_919077_12, // pointer to config struct
        ei_dsp_config_919077_12_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_919077_12_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_919077_12, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_919077_8 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_919077_8_init,
    .model_invoke = &tflite_learn_919077_8_invoke,
    .model_reset = &tflite_learn_919077_8_reset,
    .model_input = &tflite_learn_919077_8_input,
    .model_output = &tflite_learn_919077_8_output,
};

const uint8_t ei_output_tensors_indices_919077_8[1] = { 0 };
const uint8_t ei_output_tensors_size_919077_8 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_919077_8 = {
    .implementation_version = 1,
    .block_id = 8,
    .output_tensors_indices = ei_output_tensors_indices_919077_8,
    .output_tensors_size = ei_output_tensors_size_919077_8,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_919077_8,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_919077_1_size = 1;
const uint32_t ei_learning_block_919077_8_inputs[1] = { 12 };
const uint8_t ei_learning_block_919077_8_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_919077_1[ei_learning_blocks_919077_1_size] = {
    {
        8,
        &run_nn_inference,
        (void*)&ei_learning_block_config_919077_8,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_919077_8_inputs,
        ei_learning_block_919077_8_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_919077_8 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_919077_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_919077_1[ei_postprocessing_blocks_919077_1_size] = {
    {
        .block_id = 8,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_919077_8,
        .input_block_id = 8
    },
};

const uint8_t freeform_outputs_919077_1_size = 0;

uint32_t *freeform_outputs_919077_1 = nullptr;

const ei_impulse_t impulse_919077_1 = {
    .project_id = 919077,
    .project_owner = "Louie123",
    .project_name = "gesture control",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 5,

    .nn_input_frame_size = 56,
    .raw_sample_count = 150,
    .raw_samples_per_frame = 8,
    .dsp_input_frame_size = 150 * 8,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_919077_1_size,
    .dsp_blocks = ei_dsp_blocks_919077_1,

    .learning_blocks_size = ei_learning_blocks_919077_1_size,
    .learning_blocks = ei_learning_blocks_919077_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_919077_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_919077_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "ax + ay + az + acc_mag + gx + gy + gz + gyro_mag",
    .slice_size = (150/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 5,
    .categories = ei_classifier_inferencing_categories_919077_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_919077_1_size,
    .freeform_outputs = freeform_outputs_919077_1
};

ei_impulse_handle_t impulse_handle_919077_1 = ei_impulse_handle_t( &impulse_919077_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_919077_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_919077_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_919077_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_919077_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
