/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 19.04.2026 15:22:21

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 2368;
#else
constexpr int kTensorArenaSize = 1344;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,56 } };
const TfArray<1, float> quant0_scale = { 1, { 0.053136494010686874, } };
const TfArray<1, int> quant0_zero = { 1, { -45 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 8, 7, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 8, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 4, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 4, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 32, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[5] = { 229, -188, 146, -289, 200, };
const TfArray<1, int> tensor_dimension6 = { 1, { 5 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00014505762374028563, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[5*20] = { 
  -24, -96, 75, -30, 82, -75, -82, 16, 101, 17, 43, -49, -90, -105, -98, -80, -89, -27, -104, 75, 
  -77, -59, 70, 84, -39, 26, 18, 90, 7, 49, 20, -81, -45, 45, 100, 49, -4, 46, -15, 33, 
  -32, -59, 89, -41, 13, 37, -26, -19, 15, 19, -85, -36, 84, -9, -98, -56, -76, -40, 70, -110, 
  -127, -112, -54, -99, 6, 64, 6, -67, -24, -53, 99, -90, 45, 17, 69, -13, 91, -63, 27, 84, 
  -80, -39, -104, -47, 82, -61, -12, 67, 97, 62, 67, -14, -61, 35, -17, 29, 80, 4, -72, -92, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 5,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0047847679816186428, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[20] = { 746, 212, 312, -195, 729, -103, -24, -231, -53, -179, 566, 0, -121, -29, 351, -337, -139, 75, -428, 324, };
const TfArray<1, int> tensor_dimension8 = { 1, { 20 } };
const TfArray<1, float> quant8_scale = { 1, { 9.3732734967488796e-05, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[20*32] = { 
  80, -77, 73, -63, 45, 55, -31, -5, 16, 12, 44, 64, -29, -66, 105, -27, -60, -33, 100, -63, 22, 2, 104, 37, 112, 15, -88, 119, -38, -66, -3, -51, 
  43, -49, 93, 74, -61, 16, 44, -42, -66, 61, 104, -79, -40, 11, 12, -50, 7, -84, -14, -38, -44, 92, 27, 115, -4, 4, -55, -75, 7, -33, -16, 87, 
  -64, -67, 46, 83, 90, -90, 20, 70, -3, -7, 20, -66, -71, 75, 92, -13, 27, -36, 77, -102, 8, 91, 52, 17, 53, -38, 79, -33, -107, -68, 64, -59, 
  5, -48, -17, 92, 56, -59, -74, -69, -44, 24, -2, 10, -94, -3, -63, 81, -37, 59, -53, -79, -34, 41, 66, -54, -64, -14, 39, -73, 49, -41, 70, -49, 
  75, -71, -6, -27, -63, 102, -52, 15, -53, 95, -37, -65, 37, -64, -19, -38, 30, 118, 53, 94, 95, -53, 101, 69, 84, 35, -99, 86, -56, 74, -82, 1, 
  -19, 6, 16, 53, -18, -43, -83, 11, 22, -96, 67, 61, -3, 81, -65, 86, -41, -84, -76, -74, -19, -23, -58, -18, 26, -82, 4, -47, -61, 53, 46, 76, 
  67, 110, 29, 103, 61, -77, 47, -7, -4, -20, -10, 77, 86, 25, 11, -34, -40, 68, 26, 24, -101, 13, -2, 6, -95, 76, 11, -70, 92, -7, 58, -42, 
  -34, 88, 34, 34, -54, 85, -66, 32, 18, -36, 77, 8, -12, 104, 29, -62, 86, -118, -56, -22, -30, 58, -13, 0, -36, 23, 37, 73, -12, -49, 7, -99, 
  98, -19, -45, 25, -68, 63, -29, -10, 3, -61, 32, -45, 97, -21, -30, 30, -27, 40, 19, 77, 110, -9, 41, 88, 51, 20, -94, 60, -2, 37, -24, -84, 
  -77, 19, 52, 13, 13, 75, 24, -95, -32, -67, -74, 27, -7, 84, -73, 48, -55, 45, -72, 7, -72, -70, -9, -94, 89, -92, 56, -2, 18, 90, -25, -21, 
  -42, 62, 1, -30, 46, 20, -48, -73, 37, 28, 17, 60, 5, -2, -41, -20, -19, -17, -99, -59, -56, 24, 83, -79, 36, -11, 68, -50, 77, 127, 62, -19, 
  0, -26, -94, -74, 59, -92, 74, -30, -92, 7, 78, 24, -76, -45, -29, 10, -45, 15, -67, -46, -81, -35, 1, -87, 19, -88, -22, 78, -39, 13, -4, -81, 
  -29, 77, 97, -67, -4, -106, 83, 11, -9, 26, -54, 32, 74, -94, -22, 25, 46, 26, -59, -9, -87, -29, 80, -10, -21, -29, -41, 13, 58, -48, 104, 98, 
  -89, -22, -7, 39, -99, 51, -54, -73, 75, 71, -62, 68, 57, -16, -36, -13, 22, 89, 30, 95, -10, -58, -45, 9, 46, 27, -74, 1, -44, 66, -44, 103, 
  -89, 67, -7, -91, -34, -89, 55, -13, 89, 51, 20, 44, -63, 72, 62, 77, 83, -68, -93, -25, 58, -21, -67, 63, -46, 71, 99, -65, 116, 42, -11, -23, 
  32, -81, -59, -77, 13, -72, -41, -11, -86, 21, 24, -75, -40, -30, 46, -76, 61, 42, -4, -44, -80, 62, -94, -37, 23, 1, 6, 58, 28, -40, -76, -67, 
  -4, 46, 5, 7, -3, 69, -74, -8, 72, 67, -83, -77, 58, 12, -24, -45, 18, 107, -7, 112, -104, 20, -38, -36, -46, 37, 61, 11, 85, 113, -14, 116, 
  -84, 33, 9, 97, 94, 81, 38, 14, -102, 60, 0, 72, -94, -4, 59, -38, -69, 3, -22, -50, 17, -56, -27, -23, 33, 68, 62, -53, -16, 52, 23, -40, 
  57, -68, 33, 67, -81, -7, 72, 41, -38, -41, -84, -107, 51, -5, 79, -9, -83, 32, 67, 36, -14, -70, -66, 74, -3, -49, 77, -11, 94, 74, 75, -35, 
  37, -99, 66, 79, 17, 48, -36, -68, 59, 5, 15, -66, -20, 79, 65, -109, 98, 16, -48, -113, 36, 89, -82, -57, 82, 16, 23, 35, 107, 102, 32, -90, 
};
const TfArray<2, int> tensor_dimension9 = { 2, { 20,32 } };
const TfArray<1, float> quant9_scale = { 1, { 0.003564285347238183, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[16] = { 264, 207, 199, 689, 633, 325, 610, -285, 597, 894, 732, 439, 353, 1025, 228, 294, };
const TfArray<1, int> tensor_dimension10 = { 1, { 16 } };
const TfArray<16, float> quant10_scale = { 16, { 7.4186165875289589e-05, 6.8345594627317041e-05, 7.5226293120067567e-05, 6.8515204475261271e-05, 8.1398189649917185e-05, 7.3221097409259528e-05, 7.1979360654950142e-05, 7.1165537519846112e-05, 7.4956158641725779e-05, 6.5627849835436791e-05, 6.9816233008168638e-05, 7.8742225014138967e-05, 6.7592998675536364e-05, 7.8656063124071807e-05, 7.3152281402144581e-05, 6.0983638832112774e-05, } };
const TfArray<16, int> quant10_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[16*1*3*16] = { 
  /* [0][0][][] */ 43,71,72,89,-53,-6,30,64,15,27,14,1,-64,35,78,-63, 56,74,51,56,-79,-76,60,43,-4,30,73,102,91,3,-17,-118, -50,-42,29,-36,-54,-31,63,-79,-27,51,80,26,127,101,37,-100, 
  /* [1][0][][] */ -26,91,28,70,31,-119,-39,71,-55,-54,-62,-20,114,125,65,94, 115,34,53,-110,-17,-97,-15,13,11,13,50,-34,-86,-80,98,-49, 43,127,118,22,8,55,51,-60,109,17,-33,-109,-3,123,-114,21, 
  /* [2][0][][] */ -22,21,-7,-5,20,-9,12,38,90,37,94,59,45,-101,2,85, -79,28,42,-73,-36,42,93,-19,86,102,-15,-14,-101,10,103,68, -47,109,-49,-51,55,19,-38,-96,-9,-63,127,26,46,-4,-28,-15, 
  /* [3][0][][] */ 45,-27,48,-70,120,-44,-61,87,60,-115,-19,82,26,-23,-41,51, -50,12,-25,-76,77,-54,75,79,116,-93,27,6,37,-52,-73,-27, 28,-20,-96,-56,-49,35,21,127,-94,25,100,21,-27,-36,62,122, 
  /* [4][0][][] */ -22,-89,-39,-17,-91,-88,-7,25,-32,-40,-29,-31,-17,61,37,-47, 21,49,64,-19,-78,113,-43,-10,-44,-18,5,51,33,36,116,-61, -13,85,0,12,-103,127,-80,11,-14,-1,42,40,76,-34,98,32, 
  /* [5][0][][] */ -110,68,26,65,-36,-106,-23,121,-69,67,-11,-43,72,82,-80,-9, -69,127,42,57,-8,13,-49,93,-12,76,-18,4,62,11,-28,-99, -122,-3,-4,47,85,33,51,90,79,63,-33,111,-80,73,45,-9, 
  /* [6][0][][] */ 123,-16,76,85,-75,-9,53,38,53,-60,54,-59,6,-6,36,75, -7,-104,-41,56,14,54,-58,-58,-56,-1,127,-66,-62,44,-42,-27, 115,14,-82,-91,40,105,54,6,53,127,106,-38,-6,-14,105,125, 
  /* [7][0][][] */ 0,56,11,-127,-88,96,86,60,73,82,69,101,83,56,48,85, 20,0,-83,-33,88,55,125,38,-28,116,4,-117,81,-47,45,43, -64,68,7,83,-53,98,97,67,-78,6,12,-1,-30,-49,-59,91, 
  /* [8][0][][] */ 81,-117,115,98,-8,-26,62,48,-24,-55,-69,91,95,-34,-83,65, -54,-63,70,83,36,55,-44,-33,44,-108,123,-25,-8,-74,89,-51, -36,66,-8,3,19,93,-75,11,-53,-61,-36,39,18,28,127,52, 
  /* [9][0][][] */ 63,-30,60,89,-9,77,81,84,-13,-55,-24,-78,18,84,-28,49, 3,-28,-48,120,3,42,-20,122,-5,95,-94,-73,-52,127,-15,122, -9,-54,95,-89,34,-21,-75,-40,-66,28,58,18,2,65,28,-54, 
  /* [10][0][][] */ -57,-28,-29,65,12,-11,75,-34,-78,-56,3,5,-57,-87,-57,65, -74,26,-52,92,-106,67,-23,116,-17,52,-33,115,14,69,85,97, 124,-108,100,-3,-54,-60,68,114,62,127,-123,35,46,31,-41,-2, 
  /* [11][0][][] */ -49,7,-29,82,94,28,-58,-48,-32,-61,48,-5,127,-68,22,34, -44,8,-63,42,-52,-50,-68,-49,109,83,71,-59,40,-93,65,-90, -41,27,-98,14,-64,-61,-39,-73,-6,-58,-38,-12,-98,-33,26,-100, 
  /* [12][0][][] */ -70,81,-75,109,-28,18,94,-13,56,-22,-76,-30,-70,44,-69,-7, 102,99,106,44,74,-120,-78,88,-127,-99,-58,-14,33,79,-13,35, 44,-13,-42,-54,29,-114,-33,-28,-23,-4,36,-40,35,-37,-15,44, 
  /* [13][0][][] */ 9,11,-28,-40,-55,53,-46,-23,95,14,-42,29,-62,-54,-19,-48, -8,48,125,15,94,-99,-97,63,10,-33,-23,-59,85,-39,42,-36, -17,-6,-118,-57,-83,127,60,65,-33,-67,69,-101,41,-10,36,88, 
  /* [14][0][][] */ 46,41,69,-26,-18,83,44,-81,-41,112,119,-6,-18,-16,28,-67, 103,-102,29,127,-17,-56,11,-99,87,-19,-11,-8,-113,66,23,-35, 101,97,59,76,37,37,99,5,-93,100,-25,-42,-23,15,-102,36, 
  /* [15][0][][] */ 69,110,-1,-71,55,-50,-35,69,11,-9,98,-61,8,-45,5,43, -41,-77,72,-100,-104,-2,14,45,73,-65,36,-51,46,86,-32,64, 22,-52,124,2,-44,82,30,127,71,-33,111,-111,98,91,-89,-44, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 16,1,3,16 } };
const TfArray<16, float> quant11_scale = { 16, { 0.0024399966932833195, 0.0022478990722447634, 0.0024742067325860262, 0.0022534776944667101, 0.0026772015262395144, 0.0024082553572952747, 0.0023674143012613058, 0.0023406476248055696, 0.0024653219152241945, 0.0021585121285170317, 0.0022962687071412802, 0.0025898462627083063, 0.0022231461480259895, 0.0025870124809443951, 0.0024059920106083155, 0.0020057631190866232, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[16] = { 376, 602, 448, 587, -17, 534, -185, 537, 145, 25, 243, -211, 50, -186, 451, -110, };
const TfArray<16, float> quant12_scale = { 16, { 0.00012805758160538971, 0.00015287120186258107, 0.00014747123350389302, 0.0001399454049533233, 0.0001217621102114208, 0.00016561047232244164, 0.00012468635395634919, 0.0001420198823325336, 0.00014861379167996347, 0.00015466930926777422, 0.00015213584993034601, 0.00013155561464373022, 0.0001249156630365178, 0.00015009049093350768, 0.00013866592780686915, 0.00013044411025475711, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[16*1*3*7] = { 
  /* [0][0][][] */ 32,-21,-88,100,-51,59,127, -123,-23,6,70,73,76,17, 66,-104,30,98,53,106,71, 
  /* [1][0][][] */ -127,-47,-70,-96,-15,-47,57, 124,-118,107,47,30,44,-62, -61,18,-29,11,-81,2,82, 
  /* [2][0][][] */ 102,-79,-99,70,-35,75,81, -65,61,70,122,17,41,-78, 30,-49,-122,127,73,17,69, 
  /* [3][0][][] */ -71,8,119,113,115,10,-4, 50,127,39,79,103,59,110, 114,73,93,53,-40,-109,-93, 
  /* [4][0][][] */ 116,-35,-61,3,-18,-87,76, -48,-37,-61,-60,-105,-127,-48, 103,-40,-126,43,-66,-27,90, 
  /* [5][0][][] */ -50,3,26,-31,13,-56,-3, -58,-89,6,-37,88,-37,-4, -92,-127,44,51,-32,62,-100, 
  /* [6][0][][] */ 64,7,-31,-52,-103,-80,-61, -15,-87,35,-56,-17,-68,99, 48,-24,98,-93,-127,-57,-27, 
  /* [7][0][][] */ 109,66,80,-107,-58,127,97, -55,-19,-33,-53,-112,93,0, 123,-20,79,-7,31,77,-19, 
  /* [8][0][][] */ 30,35,-27,-64,-55,-99,-89, 13,-49,-127,-4,61,-16,-102, -87,63,-73,-21,-36,67,37, 
  /* [9][0][][] */ -87,50,97,90,-9,-48,-68, 4,-61,127,-73,3,-51,-17, 14,-89,80,52,-83,-56,6, 
  /* [10][0][][] */ 122,-3,-120,63,34,-81,-94, 70,-82,37,-28,-12,-91,-99, -127,7,64,-85,-102,-63,-22, 
  /* [11][0][][] */ -36,-95,-51,-10,-127,-90,26, -36,56,7,91,98,86,-117, 30,106,25,61,11,86,-62, 
  /* [12][0][][] */ -63,127,28,116,10,74,69, 85,-59,-105,-92,-11,-43,29, -1,47,-90,-72,119,70,51, 
  /* [13][0][][] */ 40,53,23,-10,49,108,82, 22,18,74,-16,-106,-84,55, 127,79,-27,15,-63,-11,-84, 
  /* [14][0][][] */ 88,31,-64,-53,-82,-10,-62, -46,76,-29,70,59,-25,8, -74,-127,-125,72,106,-88,-126, 
  /* [15][0][][] */ -31,53,25,82,-48,-127,-110, 18,99,15,42,-24,-41,84, 73,-100,125,-84,-32,-67,6, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 16,1,3,7 } };
const TfArray<16, float> quant13_scale = { 16, { 0.0024099743459373713, 0.0028769529890269041, 0.0027753286994993687, 0.0026336966548115015, 0.0022914968430995941, 0.0031166994012892246, 0.0023465296253561974, 0.0026727372314780951, 0.0027968310751020908, 0.0029107925947755575, 0.0028631142340600491, 0.0024758053477853537, 0.0023508449085056782, 0.0028246217407286167, 0.002609617542475462, 0.0024548873770982027, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,1,8,7 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,1,8,16 } };
const TfArray<1, float> quant15_scale = { 1, { 0.030404208227992058, } };
const TfArray<1, int> quant15_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&quant15_zero, 0 };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,8,1,16 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,4,1,16 } };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,1,4,16 } };
const TfArray<1, float> quant19_scale = { 1, { 0.026297764852643013, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant15_zero, 0 };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,2,1,16 } };
const TfArray<2, int> tensor_dimension22 = { 2, { 1,32 } };
const TfArray<2, int> tensor_dimension23 = { 2, { 1,20 } };
const TfArray<1, float> quant23_scale = { 1, { 0.030316542834043503, } };
const TfLiteAffineQuantization quant23 = { (TfLiteFloatArray*)&quant23_scale, (TfLiteIntArray*)&g0::quant15_zero, 0 };
const TfArray<2, int> tensor_dimension24 = { 2, { 1,5 } };
const TfArray<1, float> quant24_scale = { 1, { 0.057480767369270325, } };
const TfArray<1, int> quant24_zero = { 1, { -7 } };
const TfLiteAffineQuantization quant24 = { (TfLiteFloatArray*)&quant24_scale, (TfLiteIntArray*)&quant24_zero, 0 };
const TfArray<1, float> quant25_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant15_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 14 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 14,13,12 } };
const TfArray<1, int> outputs1 = { 1, { 15 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 15,2 } };
const TfArray<1, int> outputs2 = { 1, { 16 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 16 } };
const TfArray<1, int> outputs3 = { 1, { 17 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 17,3 } };
const TfArray<1, int> outputs4 = { 1, { 18 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 18,11,10 } };
const TfArray<1, int> outputs5 = { 1, { 19 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 19,4 } };
const TfArray<1, int> outputs6 = { 1, { 20 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 20 } };
const TfArray<1, int> outputs7 = { 1, { 21 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 21,5 } };
const TfArray<1, int> outputs8 = { 1, { 22 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 22,9,8 } };
const TfArray<1, int> outputs9 = { 1, { 23 } };
const TfLiteFullyConnectedParams opdata10 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs10 = { 3, { 23,7,6 } };
const TfArray<1, int> outputs10 = { 1, { 24 } };
const TfLiteSoftmaxParams opdata11 = { 1 };
const TfArray<1, int> inputs11 = { 1, { 24 } };
const TfArray<1, int> outputs11 = { 1, { 25 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 56, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 100, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension10, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 336, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 256), (TfLiteIntArray*)&g0::tensor_dimension14, 56, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension15, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension17, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 256), (TfLiteIntArray*)&g0::tensor_dimension18, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 192), (TfLiteIntArray*)&g0::tensor_dimension18, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension17, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension21, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension22, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension23, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant23))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension24, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant24))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[12] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[12] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 26, };
const size_t tflNodes_subgraph_index[] = {0, 12, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  25, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_919077_8_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 26;
  for (size_t i = 0; i < 26; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919077_8_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919077_8_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919077_8_invoke() {
  for (size_t i = 0; i < 12; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_919077_8_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
